hotfix(ci): fix file changes detection in update servers workflow

diff --git a/.github/workflows/update-servers-list.yml b/.github/workflows/update-servers-list.yml
--- a/.github/workflows/update-servers-list.yml
+++ b/.github/workflows/update-servers-list.yml
@@ -66,11 +66,18 @@ jobs:
 
       - name: Check for changes
         run: |
-          git diff --exit-code internal/storage/servers.json >/dev/null
+          if git diff --exit-code internal/storage/servers.json >/dev/null; then
+            echo "Error: internal/storage/servers.json was not modified."
+            exit 1
+          fi
 
       - name: Check no other file changes
         run: |
-          ! git diff --exit-code ':!internal/storage/servers.json' >/dev/null
+          if ! git diff --exit-code --quiet ':!internal/storage/servers.json'; then
+            echo "Error: Unexpected changes detected in files other than servers.json"
+            git status --short
+            exit 1
+          fi
 
       - name: Create Pull Request
         id: createpr
